version: "3.9"
services:
  web:
    image: nginx:1.19.0-alpine
    container_name: web
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_network

  backend:
    container_name: backend
    image: shehanchalaka/data-backend
    restart: always
    ports:
      - 8080:8080
    environment:
      - PORT=${PORT}
      - NODE_ENV=production
      - DB_URL=${DB_URL}
      - ETHEREUM_RPC_URL=${ETHEREUM_RPC_URL}
      - AVALANCHE_RPC_URL=${AVALANCHE_RPC_URL}
      - ANALYTICS_MAINNET_SUBGRAPH_URL=${ANALYTICS_MAINNET_SUBGRAPH_URL}
      - ANALYTICS_AVALANCHE_SUBGRAPH_URL=${ANALYTICS_AVALANCHE_SUBGRAPH_URL}
      - RAW_DATA_MAINNET_SUBGRAPH_URL=${RAW_DATA_MAINNET_SUBGRAPH_URL}
      - RAW_DATA_ACALANCHE_SUBGRAPH_URL=${RAW_DATA_ACALANCHE_SUBGRAPH_URL}
      - PRICE_FEED_MAINNET_SUBGRAPH_URL=${PRICE_FEED_MAINNET_SUBGRAPH_URL}
      - PRICE_FEED_AVALANCHE_SUBGRAPH_URL=${PRICE_FEED_AVALANCHE_SUBGRAPH_URL}
    networks:
      - my_network

networks:
  my_network:
    external: true